단어 정보를 가져와 DB에 저장하는 API 추가 #18
word-way/word-way-backend pull request #24
Opened 2020-01-04 08:22 UTC by kimdoori

# 주요 변경 사항
* 우리말샘 API 셋팅 관련 코드 추가
* word의 target_code를 unique key로
* 단어 정보를 가져와 DB에 저장하는 API 추가 #18 
  * 유의어는 wordnet을 이용해야할 것 같아서 이 PR에는 포함하지 않았습니다.

# DB

## pronunciation
<img width="427" alt="pronunciation" src="https://user-images.githubusercontent.com/22957868/71762733-a1e2c200-2f16-11ea-92ee-30a2e1a151d7.png">

## word
<img width="1252" alt="word" src="https://user-images.githubusercontent.com/22957868/71762735-a27b5880-2f16-11ea-8068-c0e6904c02ff.png">

<img width="1250" alt="sentence" src="https://user-images.githubusercontent.com/22957868/71762734-a27b5880-2f16-11ea-9703-f56fbd25a1ed.png">
<img width="1248" alt="word_sentenct_assoc" src="https://user-images.githubusercontent.com/22957868/71762736-a313ef00-2f16-11ea-9899-cba9762c6e26.png">

2020-01-09 16:08 UTC, zoripong requested changes

2020-01-09 16:08 UTC, zoripong commented on README.md
> +    alembic revision --autogenerate
ㅋㅋㅋㅋ 🤦‍♀

2020-01-09 16:08 UTC, zoripong commented on word_way/utils.py
> +        '명사': WordPart.noun,
이거 차라리 enum의 값을 한국어로 설정해서 쓰는건 어떨까여?

2020-01-09 16:08 UTC, zoripong commented on word_way/word_data.py
> +""":mod:`word_way.word_data` --- 단어 정보 저장(DB)과 관련된 API
`word_way.word_data` 보다는 `word_way.api.word`, `word_way.api.scraping` 이런식은 어떤가요?

2020-01-09 16:08 UTC, zoripong commented on word_way/word_data.py
> +import requests
```suggestion
import ... from requests
```

2020-01-09 16:08 UTC, zoripong commented on word_way/word_data.py
> +
전체적으로 알파벳으로 import 해주세요.

2020-01-09 16:08 UTC, zoripong commented on word_way/word_data.py
> +__all__ = 'word_data', 'save_word_data'
1. 크게 필요없긴 합니당
2. 트레일링 컴마 추가해주세요

2020-01-09 16:08 UTC, zoripong commented on word_way/word_data.py
> +word_data = Blueprint('word_data', __name__, url_prefix='/word_data')
blueprint name과 url도 파일명과 동일한 식으로 네이밍 바꿔주세요. data라는 단어는 좋지 않은 것 같습니다.

2020-01-09 16:08 UTC, zoripong commented on word_way/word_data.py
> +@word_data.route('/save/', methods=['POST'])
save라는 의미는 post에 담겨있어서 없는 것이 더 자연스러울 것 같네요.
https://meetup.toast.com/posts/92 디자인 가이드의 4-1을 참고해주세요

2020-01-09 16:08 UTC, zoripong commented on word_way/word_data.py
> +    '''우리말샘 API로 단어 정보를 가져와서 DB에 저장하는 API'''
endpoint, request payload, response payload에 대한 주석이 있으면 좋을 것 같네요.

2020-01-09 16:08 UTC, zoripong commented on word_way/word_data.py
> +    res = requests.get(config.get('url') + 'search', params=params)
urljoin을 사용해주세용. 무심코 설정을 바꾸어도 문제가 발생하지 않도록 방지할 수 있습니다.
```python
>>> from urllib.parse import urljoin
>>> urljoin('http://google.com', '/list')
'http://google.com/list'
>>> urljoin('http://google.com/', '/list')
'http://google.com/list'
>>> urljoin('http://google.com/', 'list')
'http://google.com/list'
>>> urljoin('http://google.com', 'list')
'http://google.com/list'
```

2020-01-09 16:08 UTC, zoripong commented on word_way/word_data.py
> +    res = requests.get(config.get('url') + 'search', params=params)
```python
res.raise_for_status()
```
API 서버로부터 정상적으로 응답이 오지 않을 것을 고려해주세요.

2020-01-09 16:08 UTC, zoripong commented on word_way/word_data.py
> +        abort(404)
```suggestion
        raise NotFound('sadf')
```
1. 저는 직관적인 `NotFound`, `BadRequest`를 raise하는 것을 좀 더 선호하긴 합니다.
2. 에러의 이유도 적어주세요.

2020-01-09 16:08 UTC, zoripong commented on word_way/word_data.py
> +              tree: elemTree.ElementTree) -> typing.Sequence[Word]:
```suggestion
def save_ward(
    target_word: str,
    tree: elemTree.ElementTree,
) -> typing.Sequence[Word]:
```
지극히 개인 취향이긴 한데 앞으로 이런식으로 하는건 어떨까요?
이렇게 하면 좀 더 읽기 편하고 인자 추가 제거에 변동받는 라인수가 줄어듭니다.

2020-01-09 16:08 UTC, zoripong commented on word_way/word_data.py
> +    '''단어 정보를 DB에 저장합니다.'''
파라미터, 리턴 값에 대한 정보도 주석에 있으면 좋을 것 같습니다. (nice to)
다른 함수들도 마찬가지

2020-01-09 16:08 UTC, zoripong commented on word_way/word_data.py
> +    ).first()
`one_or_none`을 이용하면 여러 행이 리턴되면 에러가 나기 때문에 좋습니다.
(하나의 발음에는 하나의 행만 존재해야 하기 때문에)

2020-01-09 16:08 UTC, zoripong commented on word_way/word_data.py
> +            # 단어 기본 정보 저장
이 주석없어도 될 것 같아요 (코드 보면 바로 알 수 있어서)

2020-01-09 16:08 UTC, zoripong commented on word_way/word_data.py
> +    # 발음이 없다면 저장
이 주석없어도 될 것 같아요 (코드 보면 바로 알 수 있어서)

2020-01-09 16:08 UTC, zoripong commented on word_way/word_data.py
> +            session.commit()
for문 밖에서 commit 하는 것이 효과적 일 것 같네요.

2020-01-09 16:08 UTC, zoripong commented on word_way/word_data.py
> +    res = requests.get(config.get('url') + 'view', params=params)
- 여기도 urljoin 사용해주세요.
- `res.raise_for_status()`

2020-01-09 16:08 UTC, zoripong commented on word_way/word_data.py
> +            session.commit()
단어의 예문까지 성공적으로 불러오지 못했다면 커밋하지 않는 것이 맞는 것 같아요.

2020-01-09 16:08 UTC, zoripong commented on word_way/word_data.py
> +        session.commit()
이 커밋은 없는게 나을 것 같아요.

2020-01-09 16:08 UTC, zoripong commented on word_way/word_data.py
> +    session.commit()
이 커밋도 없는게 나을 것 같아요.

2020-01-09 16:08 UTC, zoripong commented on word_way/word_data.py
> +                Word.target_code == target_code).first()
```suggestion
            word = session.query(Word).filter(
                Word.target_code == target_code
            ).first()
```
스타일차이긴 한데 이렇게 하면 훨씬 더 가독성이 좋아집니다..

2020-01-09 16:08 UTC, zoripong commented on word_way/word_data.py
> +                Word.target_code == target_code).first()
단어정보 쓸 것 없다면 `exists()`로 확인해도 될 것 같네요.

2020-01-09 16:10 UTC, zoripong commented on word_way/models.py
> +    target_code = Column(Integer, unique=True)
혹시 이 PR 보면서 생각난건데 `Pronunciation.pronunciation`에도 uniquekey 걸어주실 수 있을까요? 이 리비전에서 하면 될 것 같은데 :pray:

2020-01-10 00:53 UTC, kimdoori commented on word_way/word_data.py
> +        session.commit()
없으면 에러 납니다

2020-01-10 01:08 UTC, kimdoori commented on word_way/word_data.py
> +""":mod:`word_way.word_data` --- 단어 정보 저장(DB)과 관련된 API
이거 그냥 생각 안 나서 저렇게 했다가 물어보는 거 깜빡했..
단어 정보 삭제, 수정 같은 경우가 생긴다면 여기서 다룰거니까 `word_way.api.word` 정도가 괜찮을 것 같네여

2020-01-10 01:09 UTC, kimdoori commented on word_way/word_data.py
> +
her..... 당연히 린트가 잡아줄..... 😱

2020-01-10 01:09 UTC, kimdoori commented on word_way/models.py
> +    target_code = Column(Integer, unique=True)
okok

2020-01-10 01:27 UTC, kimdoori commented on word_way/word_data.py
> +import requests
음 lint에 걸리는데.. 이렇게 바꾸는 이유가 무엇인가요?

2020-01-10 01:31 UTC, kimdoori commented on word_way/word_data.py
> +import requests
`from requests import get as requests_get`
로 변경할게여

2020-01-10 01:50 UTC, kimdoori commented on word_way/word_data.py
> +    '''단어 정보를 DB에 저장합니다.'''
아 문서화 한 번에 하려다가 깜빡했네여

2020-01-10 04:50 UTC, kimdoori commented
https://github.com/word-way/word-way-backend/pull/24#discussion_r364806311
https://github.com/word-way/word-way-backend/pull/24#discussion_r364817035
문서화

빼고 다 반영했습니다. 나머지는 일단 슬랙에서 말한.. 그 에러.. 해결하고 여기서 반영할게여 흑..

2020-01-10 08:14 UTC, zoripong commented on word_way/word_data.py
> +        session.commit()
Flush 해주새여

2020-01-10 08:15 UTC, zoripong commented on word_way/word_data.py
> +import requests
앗 ㅋㅋㅋ 요즘 프론트해서 import 반대로 썻네요 원래 third-party library는 이렇게 import하는게 lint에 맞아욤

2020-01-10 08:16 UTC, zoripong commented on word_way/word_data.py
> +
Lint 고펴쥬새요 ㅎㅅㅎㅅㅎㅅㅎㅅㅎ

2020-01-13 11:31 UTC, kimdoori commented on word_way/word_data.py
> +        session.commit()
네 없으면 에러나서 flush 로 바꾼다는 말이였는데 넘 ,, 생각없이 썼다... ㅎㅎ..

2020-01-13 11:54 UTC, kimdoori commented on word_way/utils.py
> +        '명사': WordPart.noun,
그래도 저렇게 매핑? 하는 작업은 필요해서 일단 이대로 두고 나중에 바꿀 필요가 있다면 바꾸는 것으로 해여

2020-01-13 12:02 UTC, kimdoori commented
@zoripong 다 반영했습니다! (아마도..ㅎ) 그리고 앞으로 리뷰 해주시는 사항은 작업이 늘어지는 것을 막기 위해(ㅠㅠ) 크리티컬하거나 간단한 수정이 아니면 (즉, 반드시 이 PR에서 고쳐야하는 것이 아니면) 다음 이슈로 넘기려고 합니다. 찬성하시나요?

2020-01-16 13:42 UTC, zoripong commented on word_way/api/api.py
> +""":mod:`word_way.api.api` --- Word Way API
api밑에 api 이상하네여..... ping은 앱만들때 붙여줘도 될 것 같은데..

2020-01-16 13:42 UTC, zoripong commented on word_way/api/word.py
> +""":mod:`word_way.api.word` --- 단어 정보 저장(DB)과 관련된 API
여기 저장만 올 거 아니라서 그냥 단어 정보와 관련된 API라고 하면 될 것 같아요. (나중에 수정해도 됨)

2020-01-16 13:44 UTC, zoripong commented on word_way/api/word.py
> +    '''우리말샘 API로 단어 정보를 가져와서 DB에 저장하는 API
이거 멀티라인 일 때는 `"""`으로 묶는게 린트에 더 맞긴 합니다. (나중에 수정 해도 됨)

2020-01-16 13:44 UTC, zoripong commented on word_way/api/word.py
> +        raise NotFound('가져올 단어 정보가 없습니다.')
영어가 더 좋긴한데,,,,,,,,, (나중에 고쳐도 됨)

2020-01-16 13:58 UTC, zoripong requested changes

2020-01-16 13:58 UTC, zoripong commented on word_way/api/word.py
> +    session.commit()
for문 안에 add 제외하고 `session.add_all(words)`로 바꾸는게 좋아보여요

2020-01-16 13:58 UTC, zoripong commented on word_way/api/word.py
> +        raise BadRequest('이미 정보가 있는 단어입니다.')
91번 라인에서 리턴을 하지 않기 때문에 이미 있는 단어의 경우에도 이 라인으로 도달하지 않을 것 같아요.
그리고 이미 있는 단어라고 해서 에러를 내뿜는 것 보다 그냥 스킵한다는 메시지를 리턴하면 될 것 같네요.
이유는 이 로직이 추후에 n개의 워커가 무한대로 단어들을 가져와서 진행할텐데 이미 있는 단어를 요청하게 되는 것이 맞을테고 이미 있는 단어를 요청한 것이 `BadRequest`는 아닌 것 같아요.

2020-01-16 13:58 UTC, zoripong commented on word_way/api/word.py
> +    tree: elemTree.ElementTree
trailing comma 신경 써서 달아주세욤

2020-01-16 13:58 UTC, zoripong commented on word_way/api/word.py
> +        session.commit()
여기 커밋 추가하신 이유가 있나요?

2020-01-16 13:58 UTC, zoripong commented on word_way/api/word.py
> +                exists().where(Word.target_code == target_code))
ref: https://docs.sqlalchemy.org/en/13/orm/query.html#sqlalchemy.orm.query.Query.exists

```python
q = session.query(User).filter(User.name == 'fred')
session.query(User.id).filter(q.exists()).scalar()
```
이런식으로 하면 깔꼼하겠네요

2020-01-16 13:58 UTC, zoripong commented on word_way/config.py
> +    return dict(url=url, token=token)
`get_word_api_config`를 만들기 보다 `get_config`를 만들어서 모든 설정에 대해서 리턴해주는게 더 좋겠네요. (추후 다른 PR에서 진행해도 됩니다.)
그리고 그 때에는 좀 더 구체적으로 어떤 url이고, 어떤 token인지 명시하면 좋을 것 같아요. 설정파일에 들어가는 이름과 동일하면 더 좋구욤.

2020-01-16 13:58 UTC, zoripong commented on word_way/api/word.py
> +def save_extra_info(word: Word):
Word 클래스의 함수로 들어가면 더 좋겠네요

2020-01-16 14:01 UTC, zoripong commented
>  다 반영했습니다! (아마도..ㅎ) 그리고 앞으로 리뷰 해주시는 사항은 작업이 늘어지는 것을 막기 위해(ㅠㅠ) 크리티컬하거나 간단한 수정이 아니면 (즉, 반드시 이 PR에서 고쳐야하는 것이 아니면) 다음 이슈로 넘기려고 합니다. 찬성하시나요? (ex 문서화, )

작업이 늘어지는 것에 대해서는 저도 좋지 않다고 생각해요.
그런데 `반드시 이 PR에서 고쳐야하는 것이 아니면` 이 기준은 작업자에 따라서 다르다고 생각하기 때문에 리뷰어와의 커뮤니케이션은 필요할 것 같아요.
좀 더 핑퐁 시간을 줄이기 위해서 리뷰를 다는 사람이 `다음 PR에서 해도 좋다.` 라는 의견과 함께 남겨도 좋을 것 같네요.
다만 한 가지 걱정이 드는 것은 다음 PR에서 진행한다고 이야기 하고 진행되지 않는 건들이 생길 수 있을 것 같네요. :thinking:

2020-01-16 15:27 UTC, kimdoori commented on word_way/api/word.py
> +        session.commit()
아마 여긴 계속 commit이었을 거에여. 발음은 단어 정보 전에 다루고 있기 때문에 all or nothing일 필요가 없다고 생각했습니다.

2020-01-16 15:31 UTC, kimdoori commented on word_way/api/word.py
> +""":mod:`word_way.api.word` --- 단어 정보 저장(DB)과 관련된 API
음 저는 정보 저장의 의미를 단순히 insert 뿐만 아니라 update나 delete를 포괄하는 의미로 적은 것이긴 합니다. 근데 보는 사람에 따라 그렇게 느껴지기도 하겠네여

2020-01-16 15:36 UTC, kimdoori commented on word_way/api/word.py
> +        raise BadRequest('이미 정보가 있는 단어입니다.')
작업했을 땐 단어 검색 API에서(아직 없지만) DB에 단어 정보가 없는 경우에만 이 로직을 타게 할거라 이미 있는 경우에 요청했을 경우 BadRequest 라고 판단했습니다. 어떤 요청일 경우에 대한 응답을 정해 놓지 않아서 제가 임의로 정한건데 다른 상황들도 더 생각해서 논의해보는 게 좋을 것 같네요

2020-01-16 15:40 UTC, kimdoori commented on word_way/api/word.py
> +        raise BadRequest('이미 정보가 있는 단어입니다.')
91번 라인에서 리턴을 하지 않아도 쭉 로직을 타기 때문에 이 라인에 도달합니다. 91번 라인에서 리턴을 하지 않은 이유는 하나의 발음에 다른 단어 정보가 추가 되거나, 특정 sense(단어 정보)만 저장을 못 했을 경우를 위해서 였는데,, 생각해보니 저번에 all or nothing으로 바꾸면서 뭔가 무의미하게 느껴지네여

2020-01-16 15:41 UTC, kimdoori commented on word_way/api/word.py
> +        raise BadRequest('이미 정보가 있는 단어입니다.')
근데 지금 보니 그냥 sense별로 commit을 해도 될 것 같아 보이네요🤔

2020-01-16 15:41 UTC, kimdoori commented on word_way/api/word.py
> +    tree: elemTree.ElementTree
넴 ㅠ

2020-01-16 15:41 UTC, kimdoori commented on word_way/api/word.py
> +                exists().where(Word.target_code == target_code))
넴 감사합니다 exists를 첨써봐서ㅠ

2020-01-16 15:42 UTC, kimdoori commented on word_way/api/word.py
> +    session.commit()
근데 그러면 아래 extra_info들 저장할 때 제대로 안되지 않나요?? 이건 한 번 돌려보면서 확인해볼게여

2020-01-16 15:42 UTC, kimdoori commented on word_way/api/word.py
> +def save_extra_info(word: Word):
^_ㅠ

2020-01-16 15:42 UTC, zoripong commented on word_way/api/word.py
> +""":mod:`word_way.api.word` --- 단어 정보 저장(DB)과 관련된 API
get 같은 경우에는 저장이 아니기 때문에 없는게 더 자연스러울 것 같다고 생각했어여

2020-01-16 15:44 UTC, kimdoori commented on word_way/config.py
> +    return dict(url=url, token=token)
사실 더 추가할 게 없을 것 같아서 이름 저렇게 지었는데... 생각해보니 바로 이어지는.. 유의어 가져오는.. PR에서도 이런 config 설정이 생길 것 같네요 ㅋㅋ큐 그 PR에서 반영할게여!

2020-01-16 15:48 UTC, kimdoori commented on word_way/api/word.py
> +""":mod:`word_way.api.word` --- 단어 정보 저장(DB)과 관련된 API
네 근데 이 파일이 첨 만들어졌을 때는 정보를 건들이는(?) 핸들러 용도로만 다룰 예정이었거든여.. 추가, 삭제, 수정 정도로.. 그래서 첨 이름도 이상한 word_data 였던..

2020-01-16 15:50 UTC, zoripong commented on word_way/api/word.py
> +        raise BadRequest('이미 정보가 있는 단어입니다.')
> DB에 단어 정보가 없는 경우에만 이 로직을 타게 할거라

이렇게 될 경우 API 요청이 아니라 함수를 호출하는 방식으로 진행 될 것 같아요.
애초에 저장을 클라이언트가 요청하는 경우는 드물 것 같네요. ~route 떼도 될 것 같은..~

>91번 라인에서 리턴을 하지 않아도 쭉 로직을 타기 때문에 이 라인에 도달합니다. 91번 라인에서 리턴을 하지 않은 이유는 하나의 발음에 다른 단어 정보가 추가 되거나, 특정 sense(단어 정보)만 저장을 못 했을 경우를 위해서 였는데,, 생각해보니 저번에 단어 정보를 all or nothing으로 바꾸면서 뭔가 무의미하게 느껴지네여

도달하지만 words가 not인 경우가 없지 않나요?


>근데 지금 보니 그냥 sense별로 commit을 해도 될 것 같아 보이네요🤔

이거는 여전히 반대입니다. 하나의 단어의 10개의 문장들이 있다고 하였을 때 그 중 일부만 commit 한 상태로 프로세스가 죽어버리게 될 경우 이후에 까다로워집니다.
만약 문장이 있다는 이유로 스킵을 하게 될 경우 나머지 문장에 대해서 추가를 하지 않게 되고, 
문장이 있어도 다른 문장들을 추가하려고 할 때 이미 존재하는 문장에 의해서 unique 하게 값을 넣기 까다로워지기 때문에 하나의 단어에 대해서 문장을 저장하는 것은 전부 성공하거나 전부 실패하는 경우로 나뉘어야 한다 생각합니다.

2020-01-16 15:51 UTC, kimdoori commented
> > 다 반영했습니다! (아마도..ㅎ) 그리고 앞으로 리뷰 해주시는 사항은 작업이 늘어지는 것을 막기 위해(ㅠㅠ) 크리티컬하거나 간단한 수정이 아니면 (즉, 반드시 이 PR에서 고쳐야하는 것이 아니면) 다음 이슈로 넘기려고 합니다. 찬성하시나요? (ex 문서화, )
> 
> 작업이 늘어지는 것에 대해서는 저도 좋지 않다고 생각해요.
> 그런데 `반드시 이 PR에서 고쳐야하는 것이 아니면` 이 기준은 작업자에 따라서 다르다고 생각하기 때문에 리뷰어와의 커뮤니케이션은 필요할 것 같아요.
> 좀 더 핑퐁 시간을 줄이기 위해서 리뷰를 다는 사람이 `다음 PR에서 해도 좋다.` 라는 의견과 함께 남겨도 좋을 것 같네요.
> 다만 한 가지 걱정이 드는 것은 다음 PR에서 진행한다고 이야기 하고 진행되지 않는 건들이 생길 수 있을 것 같네요. 🤔

넴 동의하시면 당연히 그렇게 할 예정이었습니당! 이건 다음 PR에서 진행하는 건 어떨까요? 정도로.. 근데 그냥 리뷰어가 먼저 달아도 되겠네여. 걱정하신 부분은,, 저도 걱정이네여..

2020-01-16 15:58 UTC, zoripong commented on word_way/api/api.py
> +""":mod:`word_way.api.api` --- Word Way API
요고 파일명 __init__.py로만 수정하고 다음 PR에 수정해도 됩니댜

2020-01-16 15:59 UTC, zoripong commented on word_way/api/word.py
> +    session.commit()
아 안에서 또 그런게 돌죠,, 뭔가 안 될 것 같은 느낌적인 느낌,,,

2020-01-16 16:01 UTC, zoripong commented
> > > 다 반영했습니다! (아마도..ㅎ) 그리고 앞으로 리뷰 해주시는 사항은 작업이 늘어지는 것을 막기 위해(ㅠㅠ) 크리티컬하거나 간단한 수정이 아니면 (즉, 반드시 이 PR에서 고쳐야하는 것이 아니면) 다음 이슈로 넘기려고 합니다. 찬성하시나요? (ex 문서화, )
> > 
> > 
> > 작업이 늘어지는 것에 대해서는 저도 좋지 않다고 생각해요.
> > 그런데 `반드시 이 PR에서 고쳐야하는 것이 아니면` 이 기준은 작업자에 따라서 다르다고 생각하기 때문에 리뷰어와의 커뮤니케이션은 필요할 것 같아요.
> > 좀 더 핑퐁 시간을 줄이기 위해서 리뷰를 다는 사람이 `다음 PR에서 해도 좋다.` 라는 의견과 함께 남겨도 좋을 것 같네요.
> > 다만 한 가지 걱정이 드는 것은 다음 PR에서 진행한다고 이야기 하고 진행되지 않는 건들이 생길 수 있을 것 같네요. 🤔
> 
> 넴 동의하시면 당연히 그렇게 할 예정이었습니당! 이건 다음 PR에서 진행하는 건 어떨까요? 정도로.. 근데 그냥 리뷰어가 먼저 달아도 되겠네여. 걱정하신 부분은,, 저도 걱정이네여..


다음 PR에서 진행한다면 이슈로 만들어두기,,? 그리고 리뷰가 진행됐던 사람이 아니더라도 누군가 가져가서 진행하기,,? (이러다 이슈가 1000만개가 되었다는,,그런 이야기,,)

2020-01-16 16:03 UTC, kimdoori commented on word_way/api/word.py
> +        raise BadRequest('이미 정보가 있는 단어입니다.')
> 이렇게 될 경우 API 요청이 아니라 함수를 호출하는 방식으로 진행 될 것 같아요.
애초에 저장을 클라이언트가 요청하는 경우는 드물 것 같네요. route 떼도 될 것 같은..

오잉 그렇군요,, 저는 클라이언트에서 단어 검색했을 때 없는 단어라면 그 때마다 요청한다고 생각했거든요,, 그래서 굉장히 많을 거라고 생각을,, 
그리고 함수가 아니라 API로 한 이유는 나중에 이 파일에 있는 API들은 전부 외부 서비스로 뺄 예정이라 그냥 미리 달아둔 것이었습니다. (굳이 지금 할 이유는 없지만 ㅋ쿠)

> 도달하지만 words가 not인 경우가 없지 않나요?

있던대요...? 같은 단어로 두 번 요청하면 저 에러 코드가 나왔습니다.

> 이거는 여전히 반대입니다. 하나의 단어의 10개의 문장들이 있다고 하였을 때 그 중 일부만 commit 한 상태로 프로세스가 죽어버리게 될 경우 이후에 까다로워집니다.
만약 문장이 있다는 이유로 스킵을 하게 될 경우 나머지 문장에 대해서 추가를 하지 않게 되고,
문장이 있어도 다른 문장들을 추가하려고 할 때 이미 존재하는 문장에 의해서 unique 하게 값을 넣기 까다로워지기 때문에 하나의 단어에 대해서 문장을 저장하는 것은 전부 성공하거나 전부 실패하는 경우로 나뉘어야 한다 생각합니다.

아뇽 제가 말한건 예문이 아니라 단어 정보를 말한겁니다. 말씀하신대로 하나의 단어 저장에 있어서 예문과 유의어 같은 추가 정보가 다 정상적으로 저장되어야 그 단어를 저장한다는 것에 동의하는데, 하나의 발음에 있어서 모든 단어가 정상적으로 저장이 되어야 모든 단어를 저장하는 건 굳이.. 라는 생각이 들어서요. 제가 언급한 sense는 우리말 샘 API에서 받아오는 xml tag 이름을 기준으로 말씀드린거라(ㅎㅎ지송) 단어 기본 정보 정도로 알아주시면 될 것 같아여. 저 sense 뽑아오는 for문 안에서 commit해도 될 것 같다는 얘기였습니다

2020-01-16 16:03 UTC, kimdoori commented on word_way/api/word.py
> +        raise BadRequest('이미 정보가 있는 단어입니다.')
113번 라인 쯤에서..!

2020-01-16 16:04 UTC, kimdoori commented on word_way/api/api.py
> +""":mod:`word_way.api.api` --- Word Way API
옛설

2020-01-16 16:05 UTC, zoripong commented on word_way/utils.py
> +        '명사': WordPart.noun,
왜 매핑하는 작업이 필요하죰?? 값을 통해 enum을 가져오게 하면 필요 없지 않나용??

2020-01-16 16:08 UTC, kimdoori commented on word_way/utils.py
> +        '명사': WordPart.noun,
Api에서 받아오는 건 str이라 어쨌든 해당 str일 때 어떤 enum인지 구해야한다고 생각했는데, https://stackoverflow.com/questions/41407414/convert-string-to-enum-in-python 그냥.. 하면되네요 ㅋㅋ.. 제가 파이썬을 별로 안해봐서,,쥬륵..

2020-01-16 16:12 UTC, zoripong commented on word_way/api/word.py
> +        raise BadRequest('이미 정보가 있는 단어입니다.')
> 오잉 그렇군요,, 저는 클라이언트에서 단어 검색했을 때 없는 단어라면 그 때마다 요청한다고 생각했거든요,, 그래서 굉장히 많을 거라고 생각을,,
그리고 함수가 아니라 API로 한 이유는 나중에 이 파일에 있는 API들은 전부 외부 서비스로 뺄 예정이라 그냥 미리 달아둔 것이었습니다. (굳이 지금 할 이유는 없지만 ㅋ쿠)

클라이언트에서 단어를 검색했을 때 없는 단어일 경우에는 이 API로 오지 않고 검색 API로 간 후 그 API에서 이 함수를 실행시키게 될거라 필요없다고 생각한겁니다. (슬랙에도 의견 남겼는데 확인해쥬세요 :pray:)



> 있던대요...? 같은 단어로 두 번 요청하면 저 에러 코드가 나왔습니다.

아 아 그렇네요 착각쓰 😅

> 아뇽 제가 말한건 예문이 아니라 단어 정보를 말한겁니다. 말씀하신대로 하나의 단어 저장에 있어서 예문과 유의어 같은 추가 정보가 다 정상적으로 저장되어야 그 단어를 저장한다는 것에 동의하는데, 하나의 발음에 있어서 모든 단어가 정상적으로 저장이 되어야 모든 단어를 저장하는 건 굳이.. 라는 생각이 들어서요. 제가 언급한 sense는 우리말 샘 API에서 받아오는 xml tag 이름을 기준으로 말씀드린거라(ㅎㅎ지송) 단어 기본 정보 정도로 알아주시면 될 것 같아여. 저 sense 뽑아오는 for문 안에서 commit해도 될 것 같다는 얘기였습니다

원자성을 따져보면 for 안에서 commit이 이뤄져도 될 것 같은데 이렇게 될 경우 commit이 너무 빈번해져서 속도도 느려지고, DB에 부하도 생기기 때문에 그랬던 것도 컸습니다.

2020-01-16 16:17 UTC, kimdoori commented on word_way/api/word.py
> +        raise BadRequest('이미 정보가 있는 단어입니다.')
1. 넴 확인했고 함수로 변경할게야
3. 으으ㅡ으음... 고민..  뭐 하나의 발음에 단어가 중간에 추가 되는 경우가 얼마나 있겠어여.. 그쳐? ㅎㅎ.. 그럼 일단 모든 단어 저장이 성공할 경우 commit으로 그래도 둘게여

2020-01-17 03:48 UTC, kimdoori commented on word_way/api/word.py
> +def save_extra_info(word: Word):
hoxy,,, 이거 다음 PR에서 반영해두 되나요?

2020-01-17 03:51 UTC, zoripong commented on word_way/api/word.py
> +def save_extra_info(word: Word):
넴 대신에 이건 바로 반영해주세용

2020-01-17 03:52 UTC, zoripong commented on word_way/api/word.py
> +def save_extra_info(word: Word):
이거 별로 안 복잡한데 :eyes:

2020-01-18 15:41 UTC, zoripong requested changes
머지하기 전까지는 리뷰 반영 사항을 커밋으로 남겨두지 않고 해당 작업 내역의 커밋에 합치는게 더 좋지만,, 이것은 선택사항으로 해요,,

2020-01-18 15:41 UTC, zoripong commented on word_way/scrapping/word.py
> +import xml.etree.ElementTree as elemTree
(질문) 이거는 그냥 ElementTree로 쓰면 될 것 같은데 왜 별명 지어줬나요?

2020-01-18 15:41 UTC, zoripong commented on word_way/scrapping/word.py
> +from word_way.utils import convert_word_part
다른 파일에서는 relative import인데 통일해주세요.
pep 기준으로는 absolute import를 권장한다고 하긴 합니다.

2020-01-18 15:41 UTC, zoripong commented on word_way/scrapping/word.py
> +    if res.status_code != 200:
```sugesstion
    if res.status_code < 200 or res.status_code >= 300:
```

또는

```sugesstion
    if not res.ok:
```

2020-01-18 15:41 UTC, zoripong commented on word_way/scrapping/word.py
> +def save_word(target_word: str):
```suggestion
def save_word(target_word: str) -> None:
```

2020-01-18 15:41 UTC, zoripong commented on word_way/scrapping/word.py
> +
return type 빠졌네여

2020-01-18 15:41 UTC, zoripong commented on word_way/scrapping/word.py
> +                literal(True)).filter(q.exists()).scalar()
```
            word_exists = session.query(
                literal(True)
            ).filter(q.exists()).scalar()
```
또는

```
            word_exists = session.query(
                literal(True)
            ).filter(
                q.exists()
            ).scalar()
```
또는 
```
            word_exists = session.query(literal(True)).filter(
                q.exists()
            ).scalar()
```

인덴트,, 잘 맞춰주세요오.. :pray:

2020-01-18 15:41 UTC, zoripong commented on word_way/scrapping/word.py
> +def save_extra_info(word: Word):
```suggestion
def save_extra_info(word: Word) -> None:
```

2020-01-18 15:41 UTC, zoripong commented on word_way/scrapping/word.py
> +    if res.status_code != 200:
여기도 위에 리뷰 단 것 처럼 변경해주세요

2020-01-18 15:41 UTC, zoripong commented on word_way/scrapping/word.py
> +def save_word_info(
이 함수는 그냥 `save_word` 이 함수에 포함되도 될 것 같아요. 너무 잘게 쪼개도 트래킹하기 힘들기 때문에

2020-01-18 15:44 UTC, zoripong commented
리뷰가 길어지고 있지만 초반이라 그런 것도 있는 것 같아욤 거의 끝이 보이니 좀 만 더 ,, 👊🔥

2020-01-19 00:37 UTC, kimdoori commented on word_way/scrapping/word.py
> +def save_word(target_word: str):
아항 맞다,,

2020-01-19 00:38 UTC, kimdoori commented on word_way/scrapping/word.py
> +
return 을 뺐는데 typehint 빼는 걸 깜빡..

2020-01-19 00:38 UTC, kimdoori commented on word_way/scrapping/word.py
> +                literal(True)).filter(q.exists()).scalar()
원래 이렇게는 잘 안쓰나요?? 저는 이런 코드도 많이 본 것 같아서.. 그리고 사실 에디터가 자동 줄바꿈 해준 거거든요 😢

2020-01-19 00:42 UTC, kimdoori commented
> 머지하기 전까지는 리뷰 반영 사항을 커밋으로 남겨두지 않고 해당 작업 내역의 커밋에 합치는게 더 좋지만,, 이것은 선택사항으로 해요,,

저는 린트나 간단한 리뷰들은 작업 커밋과 합치는 편이고, 네이밍 변경이나 로직 변경 같은 보다 눈에 보이는 변경 사항(?)은 커밋 메시지를 붙여(`리뷰 사항 반영 commit` <- 이런 거 XXX) 새로운 커밋으로 두는 편입니다!

2020-01-19 00:47 UTC, kimdoori commented on word_way/scrapping/word.py
> +import xml.etree.ElementTree as elemTree
공식 문서나 다른 예제들 보면 꼭 별칭을 쓰더라구요.. `ET` 정도로??  https://docs.python.org/3/library/xml.etree.elementtree.html
그래서 생각해보니 표준 라이브러리들은 `from ... import ...` 이렇게 잘 안쓰는 것 같아서 저렇게 두었습니다.

2020-01-19 00:48 UTC, kimdoori commented on word_way/scrapping/word.py
> +from word_way.utils import convert_word_part
으흠.. 그러면 전부 absolute import 이걸로 바꾸ㅓ볼게여

2020-01-19 00:50 UTC, kimdoori commented on word_way/scrapping/word.py
> +                literal(True)).filter(q.exists()).scalar()
일단 3번으로 변경했슴니다

2020-01-19 01:07 UTC, kimdoori commented on word_way/scrapping/word.py
> +def save_word_info(
`save_word_info` 함수에서 하는 일을 `save_word` 에서 하자는 말인가여? 그럼 너무 길어질 것 같아서.. 저는 이대로가 좋다고 느껴집니다아...
실제 서비스 전에 로깅을 붙여도 좋지 않을까요??

2020-01-19 01:09 UTC, kimdoori commented
> 리뷰가 길어지고 있지만 초반이라 그런 것도 있는 것 같아욤 거의 끝이 보이니 좀 만 더 ,, 👊🔥

ㅠㅜ.... python 을 많이 만져보지도 않았고, 만져본지 좀 지나서 자꾸 뭘 빠트리네여ㅠ 담엔 더 신경써볼게여

2020-01-19 15:26 UTC, zoripong commented on word_way/scrapping/word.py
> +def save_word_info(
> `save_word_info` 함수에서 하는 일을 `save_word` 에서 하자는 말인가여? 그럼 너무 길어질 것 같아서.. 저는 이대로가 좋다고 느껴집니다아...
> 실제 서비스 전에 로깅을 붙여도 좋지 않을까요??

합치면 50라인 정도밖에 안돼서 그렇게 길진 않은 것 같아요. 함수 이름이 너무 모호해요. `save_word` , `save_word_info` 두개 차이가 잘 느껴지지 않고 그런데, 이런 이유가 둘이 하는 동작이 <단어를 저장하는 일>인데 굳이 나눠둔 기분이 들어요

2020-01-20 01:11 UTC, kimdoori commented on word_way/scrapping/word.py
> +def save_word_info(
저는 50라인이면 길다고 느껴집니다..! 이건 사람마다 차이가 있을 것 같네요. 원래는 save_word 가 API였어서 뭔갈 쪼개보려고 한 것 같은데 듣고보니 함수로 바꼈네요 ㅋㅋㅋ,, 그리고 둘 다 단어를 저장하는 일이긴 하니 합치고, 단어 정보를 요청하는 걸 따로 빼는 게 나을 것 같네여!

2020-01-20 08:49 UTC, zoripong submitted a review, later dismissed
✨수🔥고🎁많👊으🤖셨🙏어🍏요👻

2020-01-20 10:20 UTC, kimdoori commented
@zoripong 진짜 끝ㄲ그그ㅡ트ㅡㄱ끝!!!!!

2020-01-21 05:18 UTC, zoripong approved these changes
✨수🔥고🎁많👊으🤖셨🙏어🍏요👻

2020-01-21 05:53 UTC, merged