앱 config를 설정하는 방법을 변경합니다.
word-way/word-way-backend pull request #4
Opened 2019-10-12 15:11 UTC by kimdoori

[configparser](https://docs.python.org/3/library/configparser.html#)를 사용해서 *.conf 로 앱 config를 설정하도록 변경합니다.

2019-10-12 15:15 UTC, zoripong requested changes

2019-10-12 15:15 UTC, zoripong commented on word_way/config.py
> +def load_config(config_name):
typehint 추가해주세여

2019-10-12 15:15 UTC, zoripong commented on .gitignore
> +*.conf
prod.conf는 제외 되면 안 되지 않을까유

2019-10-12 15:16 UTC, kimdoori commented on .gitignore
> +*.conf
이거 *.conf 로 다 제외시키고 prod.conf만 add -f 했습니당

2019-10-12 15:16 UTC, kimdoori commented on word_way/config.py
> +def load_config(config_name):
오케바레..

2019-10-12 16:11 UTC, zoripong commented on .gitignore
> +*.conf
앞으로 prod.conf 파일이 수정 될 때마다 신경써줘야 할 것이기 때문에 좋지 않은 방법인 것 같습니다. 충분히 작업자가 놓칠 수 있을 것 같습니다.

2019-10-12 16:11 UTC, zoripong requested changes
https://github.com/word-way/word-way-backend/pull/4/files#r334243931

2019-10-12 16:15 UTC, kimdoori commented on .gitignore
> +*.conf
한 번 스테이징(이라고 하나요?)된 파일은 수정 사항이 생기면 계속 트래킹할 수 있어서 문제 없다고 생각합니당!

2019-10-14 13:34 UTC, zoripong commented on .gitignore
> +*.conf
그건 몰랐군여

2019-10-14 13:34 UTC, zoripong approved these changes

2019-10-14 13:53 UTC, merged

2019-10-14 14:14 UTC, zoripong commented
의도적으로 남겨야 하는 브랜치가 아닌경우 삭제해쥬세요! (브랜치 관리를 위하여)

2019-10-14 14:15 UTC, kimdoori commented
녬녬!